# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/minutelists', type: :request do
  # Minutelist. As you add validations to Minutelist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Minutelist.create! valid_attributes
      get minutelists_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      minutelist = Minutelist.create! valid_attributes
      get minutelist_url(minutelist)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_minutelist_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      minutelist = Minutelist.create! valid_attributes
      get edit_minutelist_url(minutelist)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Minutelist' do
        expect do
          post minutelists_url, params: { minutelist: valid_attributes }
        end.to change(Minutelist, :count).by(1)
      end

      it 'redirects to the created minutelist' do
        post minutelists_url, params: { minutelist: valid_attributes }
        expect(response).to redirect_to(minutelist_url(Minutelist.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Minutelist' do
        expect do
          post minutelists_url, params: { minutelist: invalid_attributes }
        end.to change(Minutelist, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post minutelists_url, params: { minutelist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested minutelist' do
        minutelist = Minutelist.create! valid_attributes
        patch minutelist_url(minutelist), params: { minutelist: new_attributes }
        minutelist.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the minutelist' do
        minutelist = Minutelist.create! valid_attributes
        patch minutelist_url(minutelist), params: { minutelist: new_attributes }
        minutelist.reload
        expect(response).to redirect_to(minutelist_url(minutelist))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        minutelist = Minutelist.create! valid_attributes
        patch minutelist_url(minutelist), params: { minutelist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested minutelist' do
      minutelist = Minutelist.create! valid_attributes
      expect do
        delete minutelist_url(minutelist)
      end.to change(Minutelist, :count).by(-1)
    end

    it 'redirects to the minutelists list' do
      minutelist = Minutelist.create! valid_attributes
      delete minutelist_url(minutelist)
      expect(response).to redirect_to(minutelists_url)
    end
  end
end
